name: test

on: workflow_dispatch

jobs:
  list-md:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "test" > test.md
          echo "test" > test2.md
          echo "test" > test3.md
          echo "::set-output name=matrix::$(ls *.md | jq -R -s -c 'split("\n")[:-1]')"
  pandoc:
    needs: list-md
    runs-on: ubuntu-latest
    # container: pandoc/latex
    strategy:
      matrix: ${{ fromJson(needs.list-md.outputs.matrix) }}
    steps:
      - shell: bash
        run: pandoc -N --variable "geometry=margin=0.8in" ${{ matrix }} --pdf-engine=xelatex -o ${{ matrix }}
