name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - run: echo "files=$(printf '%s ' *.md)" > $GITHUB_OUTPUT
      - run: run.sh ${{ steps.files_list.outputs.files }}
