name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - run: | 
            echo "test" > test.md
            echo "test" > test2.md
            echo "test" > test3.md
            echo "files=$(printf '%s ' *.md)" > $GITHUB_OUTPUT
      - run: |
          FILES=${ steps.test.outputs.files }
          for f in $FILES
            do
              # extension="${f##*.}"
              filename="${f%.*}"
              echo "Converting $f to $filename.pdf"
              `pandoc -N --variable "geometry=margin=0.8in" "$f" --pdf-engine=xelatex -o "$filename.pdf"`
            done
