name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - run: echo "files=$(printf '%s ' *.md)" > $GITHUB_OUTPUT
      - run: |
          for f in ${{ steps.files_list.outputs.files }}
            do
              # extension="${f##*.}"
              filename="${f%.*}"
              echo "Converting $f to $filename.pdf"
              `pandoc -N --variable "geometry=margin=0.8in" "$f" --pdf-engine=xelatex -o "$filename.pdf"`
            done
