name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
#     container: pandoc/latex
    steps:
      - uses: actions/checkout@v3
      - name: get files
        id: files_list
        run: | 
            echo "test" > test.md
            echo "test" > test2.md
            echo "test" > test3.md
            echo "files=$(printf '%s ' *.md)" > $GITHUB_OUTPUT
            echo "${ steps.files_list.outputs.files }"
      - shell: bash
        run: | 
          echo "${{ steps.test.outputs.files }}"
          for f in "${{ steps.files_list.outputs.files }}"
            do
              # extension="${f##*.}"
              filename="${f%.*}"
              echo "Converting $f to $filename.pdf"
              `pandoc -N --variable "geometry=margin=0.8in" "$f" --pdf-engine=xelatex -o "$filename.pdf"`
            done
