name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - run: |
          FILES=*.md
            for f in $FILES
            do
              # extension="${f##*.}"
              filename="${f%.*}"
              echo "Converting $f to $filename.pdf"
              `pandoc -N --variable "geometry=margin=0.8in" "$f" --pdf-engine=xelatex -o "$filename.pdf"`
            done
